#!/bin/sh
case $BLOCK_BUTTON in
        1) amixer -q sset Capture toggle ;;
         4) amixer -q sset Capture 5%+ ;;
         5) amixer -q sset Capture 5%- ;;
         esac

volstat=$(amixer get Capture)
vol=$(echo "$volstat" | grep -o "\[[0-9]\+%\]" | sed "s/[^0-9]*//g;1q")
echo "$volstat" | grep "\[off\]" >/dev/null && printf "off\\n" && exit
echo "$vol"


