#!/bin/sh

volstat="$(amixer get Master)" 
echo "$volstat" | grep "\[off\]" >/dev/null && printf "muted\\n" && exit
vol=$(echo "$volstat" | grep -o "\[[0-9]\+%\]" | sed "s/[^0-9]*//g;1q")
echo "$vol"

	 
