#!/bin/ash
case $1 in
	1)
	 sudo ntfs-3g /dev/sda1 /home/kai/mnt/pho
	;;
	2)
	 sudo umount /home/kai/mnt/pho
	;;
	3)
	 sudo ntfs-3g /dev/sda2 /home/kai/mnt/aps
	 ;;
	4)
	sudo umount /home/kai/mnt/aps
	;;
	5)
	sudo ntfs-3g /dev/sda5 /home/kai/mnt/lib
	;;
	6)
	sudo umount /home/kai/mnt/lib
	;;
	7)
	sudo mount /dev/sda4 /home/kai/mnt/arch
	;;
	8)
	sudo umount /home/kai/mnt/arch
	;;
	*)
	echo " 
		usage mo [1-9] 
		mount-unmount 1-2=pho 3-4=aps 5-6=lib 7-8=arch"
	;;
esac	
	
